---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
  - type: standard
    ref: v4.464.0 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: cli/cli@v2.86.0
  - name: jqlang/jq@jq-1.8.1
  - name: denoland/deno@v2.6.7
  - name: neovim/neovim@v0.11.6
  - name: x-motemen/ghq@v1.8.0
  - name: junegunn/fzf@v0.67.0
  - name: direnv/direnv@v2.37.1
  - name: mislav/hub@v2.14.2
  - name: starship/starship@v1.24.2
  - name: sharkdp/fd@v10.3.0
  - name: BurntSushi/ripgrep@15.1.0
  - name: ast-grep/ast-grep@0.40.5
  - name: jdx/pitchfork@v1.2.0
